package pack01;

import java.util.ArrayList;

import modelP.Problem;

public class Solution002 extends MachineListRepSolution {

	public Solution002(Problem problem) {
		super(problem);
	}

	@Override
	public ArrayList<int[][]> createNewSolutions(ArrayList<int[][]> parentSolutions, Problem p) {
		ArrayList<int[][]> newSolutions = new ArrayList<int[][]>();
		
		ArrayList<int[]> parent1 = this.makeChromosome( parentSolutions.get(0), p );
		ArrayList<int[]> parent2 = this.makeChromosome( parentSolutions.get(1), p );
		
		ArrayList<ArrayList<int[]>> parents = new ArrayList<ArrayList<int[]>>();
		parents.add(parent1);
		parents.add(parent2);
		
		//multiple crossover points are generated by passing false as the boolean parameter
		ArrayList<Integer> crossoverPoints = this.selectCrossoverPoints( false, parent1.size() );
		
		ArrayList<ArrayList<int[]>> childrenGenomes = this.crossover( parents, crossoverPoints );
		
		int[][] child1 = this.turnChromosomeIntoSolution( childrenGenomes.get(0) );
		int[][] child2 = this.turnChromosomeIntoSolution( childrenGenomes.get(1) );
		
		newSolutions.add(child1);
		newSolutions.add(child2);
		
		return newSolutions;
	}

}
